name: unlockme
description: Unlock vehicles through QR.
version: 1.0.0+2
environment:
  sdk: ">=3.1.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  path: any
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  get: ^4.6.6
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.3
  dotted_border: ^2.1.0
  intl: ^0.19.0
  permission_handler: ^11.1.0
  images_picker: ^1.2.11
  geolocator: ^12.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.2.6
  sqflite: ^2.3.3+1
  hive: ^2.2.3
  qr_code_scanner: ^1.0.1
  hive_flutter: ^1.1.0
  flutter_xlider: ^3.5.0
  mockito: ^5.4.4
  build_runner: ^2.4.10
  http: any
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/ManropeSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ManropeBold.ttf
          weight: 700
    - family: Archivo
      fonts:
        - asset: assets/fonts/ArchivoRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/ArchivoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/ArchivoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/ArchivoRomanBold.ttf
          weight: 700
    - family: Rubik
      fonts:
        - asset: assets/fonts/RubikRomanRegular.ttf
          weight: 400
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_app.png" #for standard icon (fallback)
  adaptive_icon_background: "assets/images/background_icon.png"
  adaptive_icon_foreground: "assets/images/foreground_icon.png"
  remove_alpha_ios: true